### ISSUE TITLE
Scope scripts?

### ISSUE THREAD

**Issue by Carlos-Schrodinger** [brick-hill/docker-hill#10]
How would you add more scripts if the dockerize container cannot reach out from the VM?

**Comment by Sylack-lab** [comment]
I personally found a possible fix through binding mounts and volumes

https://flaviocopes.com/docker-access-files-outside-container/

**Comment by dnigamer** [comment]
You will basically need to set up your own volume while running the container for scripts and binding it from any host folder to container's `/usr/src/app/user_scripts`

**Comment by Carlos-Schrodinger** [comment]
Isnt it better to make an image out of the finished product?

**Comment by dnigamer** [comment]
you would need to be making new versions of the same image everytime you updated any script or added one, and that uses more space sometimes and it's way harder to do it everytime

**Comment by Carlos-Schrodinger** [comment]
> you would need to be making new versions of the same image everytime you updated any script or added one, and that uses more space sometimes and it's way harder to do it everytime

I can just use pipelines for that, github actions etc.

**Comment by Carlos-Schrodinger** [comment]
Docker for node-hill itself is a bit too much imo
